// CSV export
export const exportCSV = (rows, filename = 'export.csv') => {
  const csv = rows.map(row =>
    row.map(cell => {
      const s = String(cell ?? '').replace(/"/g, '""');
      return s.includes(',') || s.includes('"') || s.includes('\n') ? `"${s}"` : s;
    }).join(',')
  ).join('\n');

  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  triggerDownload(blob, filename);
};

// Plain text / ticket export
export const exportText = (content, filename = 'ticket.txt') => {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8;' });
  triggerDownload(blob, filename);
};

// Print / PDF helper (opens print dialog)
export const printHTML = (htmlContent, title = 'SmartPark Report') => {
  const win = window.open('', '_blank');
  if (!win) { alert('Please allow popups to generate PDF.'); return; }
  win.document.write(`
    <!DOCTYPE html><html><head>
    <title>${title}</title>
    <style>
      body { font-family: 'Segoe UI', Arial, sans-serif; padding: 32px; color: #1e293b; }
      h1 { color: #1d4ed8; font-size: 22px; margin-bottom: 4px; }
      h3 { color: #475569; font-size: 13px; font-weight: normal; margin-bottom: 24px; }
      table { width: 100%; border-collapse: collapse; font-size: 13px; }
      th { background: #f1f5f9; font-weight: 600; text-align: left; padding: 10px 14px; border: 1px solid #e2e8f0; }
      td { padding: 9px 14px; border: 1px solid #e2e8f0; }
      tr:nth-child(even) td { background: #f8fafc; }
      .badge { display: inline-block; padding: 2px 10px; border-radius: 9999px; font-size: 11px; font-weight: 600; }
      .badge-green { background: #dcfce7; color: #16a34a; }
      .badge-red { background: #fee2e2; color: #dc2626; }
      .badge-yellow { background: #fef9c3; color: #ca8a04; }
      .badge-blue { background: #dbeafe; color: #2563eb; }
      .footer { margin-top: 24px; font-size: 11px; color: #94a3b8; }
    </style>
    </head><body>${htmlContent}
    <div class="footer">Generated by SmartPark · ${new Date().toLocaleString('en-IN')}</div>
    </body></html>
  `);
  win.document.close();
  setTimeout(() => win.print(), 400);
};

// Helper
const triggerDownload = (blob, filename) => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
};

// Build booking ticket text
export const buildTicketText = (booking) => `
=======================================
          SmartPark – Parking Ticket
=======================================
Booking ID  : ${booking.bookingId}
Slot        : ${booking.slot || booking.slotId}
Location    : ${booking.location || 'SmartPark Central'}
Date        : ${booking.date}
Start Time  : ${booking.startTime}
End Time    : ${booking.endTime}
Duration    : ${booking.duration} hour(s)
Vehicle     : ${booking.vehicle}
Amount Paid : ₹${booking.cost}
Status      : CONFIRMED
=======================================
Present this ticket at the entry gate.
Thank you for using SmartPark!
`.trim();

// Build weekly report HTML for PDF
export const buildWeeklyReportHTML = (rows, meta = {}) => {
  const badgeClass = (occ) => {
    const v = parseInt(occ);
    return v >= 90 ? 'badge-red' : v >= 70 ? 'badge-yellow' : 'badge-green';
  };
  return `
    <h1>SmartPark – Weekly Parking Report</h1>
    <h3>${meta.location || 'SmartPark Central'} &nbsp;|&nbsp; Week of ${meta.week || new Date().toLocaleDateString('en-IN')}</h3>
    <table>
      <thead><tr>
        <th>Day</th><th>Reservations</th><th>Revenue</th><th>Occupancy</th>
      </tr></thead>
      <tbody>
        ${rows.map(r => `<tr>
          <td>${r.day}</td>
          <td>${r.reservations}</td>
          <td>₹${Number(r.revenue).toLocaleString('en-IN')}</td>
          <td><span class="badge ${badgeClass(r.occupancy)}">${r.occupancy}</span></td>
        </tr>`).join('')}
      </tbody>
    </table>
  `;
};
